- README.md
- go.mod
Hello @nicks,
Please review the following commits I made in branch nicks/init:
8c85794555588e539bc80c1361df31f7467a127a (2020-10-16 14:43:12 -0400)
add go.mod, and normalize randomly changing the pronunciation
> add go.mod, and normalize randomly changing the pronunciation

- go.mod
- go.sum
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/options.go
- pkg/cmd/get.go
Hello @nicks,
Please review the following commits I made in branch nicks/get:
864b41390fc39f154baf57622a3f77fadb2d5bfd (2020-10-22 11:06:16 -0400)
richer get/list options
> richer get/list options

- examples/docker-desktop.yaml
- pkg/cluster/cluster.go
- pkg/cluster/product.go
- pkg/cmd/apply.go
- pkg/cmd/root.go
- pkg/visitor/decode.go
- pkg/visitor/visitor.go
Hello @nicks,
Please review the following commits I made in branch nicks/apply:
af6070aec8d6c2c3371165a39b8d8fa4036bfe2d (2020-10-22 14:50:23 -0400)
scaffolding for an apply command
> scaffolding for an apply command

- examples/docker-desktop.yaml
- internal/printers/name.go
- pkg/api/accessors.go
- pkg/cmd/apply.go
- pkg/cmd/get.go
- pkg/cmd/printer.go
Hello @nicks,
Please review the following commits I made in branch nicks/apply:
71c5f0ea917f69b648df3bc1db7f0cdb072d6450 (2020-10-22 15:08:09 -0400)
printers: fork the apimachinery printer to work with our api types
> printers: fork the apimachinery printer to work with our api types

- pkg/cluster/cluster.go
- pkg/cluster/product.go
- pkg/cluster/product_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/minikube:
00c15ae4d836912d706f960ce6739e9036bff360 (2020-10-22 17:38:40 -0400)
cluster: better minikube detection
> cluster: better minikube detection

- go.mod
- go.sum
- pkg/api/types.go
- pkg/cluster/cluster.go
- pkg/cluster/machine.go
Hello @nicks,
Please review the following commits I made in branch nicks/ch9898:
cd26292f051d4419118a1e08128276a8fbc77036 (2020-10-22 18:17:27 -0400)
cluster: read the number of cpus off the cluster
> cluster: read the number of cpus off the cluster

- go.mod
- go.sum
- pkg/api/types.go
- pkg/api/zz_generated.deepcopy.go
- pkg/cmd/get_test.go
- pkg/registry/registry.go
- pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry:
1c0404937abaec4f8eff6d215b8bf944de9f6e2a (2020-10-26 12:24:23 -0400)
registry: add networks
> registry: add networks

- pkg/cluster/cluster.go
- pkg/cmd/apply.go
- pkg/cmd/delete.go
- pkg/cmd/delete_test.go
- pkg/cmd/root.go
- pkg/visitor/strings.go
Hello @nicks,
Please review the following commits I made in branch nicks/delete:
bfea65182378d21da16f5cd836cebf5567517287 (2020-10-26 20:34:43 -0400)
cmd: scaffolding for ctlptl delete
> cmd: scaffolding for ctlptl delete

- Makefile
- examples/docker-desktop.yaml
- pkg/api/types.go
- pkg/cluster/docker_for_mac.go
- pkg/cluster/docker_for_mac_test.go
Please review the following commits I made in branch nicks/d4mclient:
dbe2760615044466cd738669cc5ced355bb141bc (2020-10-23 11:12:05 -0400)
cluster: add a client for reading/writing docker for mac settings
> cluster: add a client for reading/writing docker for mac settings

- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/docker_for_mac.go
- pkg/cluster/machine.go
Please review the following commits I made in branch nicks/ch9899:
fa7c27d60963bd3ffc2b09e954ccc217b1e83e96 (2020-10-26 14:55:03 -0400)
cluster: ctlptl apply can change the CPU on docker for mac
45638a0896bf52b71750b076c56871184eb6d481 (2020-10-26 13:47:04 -0400)
cluster: add a client for reading/writing docker for mac settings
> cluster: ctlptl apply can change the CPU on docker for mac

- pkg/cluster/cluster.go
- pkg/cmd/delete.go
- pkg/cmd/delete_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/delete-kind:
15e6e5abde2db106d8a7fba96c87ac778adcdbdd (2020-10-29 16:40:14 -0400)
cluster: make sure kind delete works
> cluster: make sure kind delete works

- examples/registry.yaml
- internal/printers/name.go
- pkg/api/accessors.go
- pkg/api/types.go
- pkg/cmd/apply.go
- pkg/cmd/delete.go
- pkg/cmd/delete_test.go
- pkg/cmd/get.go
- pkg/encoding/encoding.go
- pkg/registry/registry.go
- pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry:
336fc4e53d6b74852690aa4f8d868b5728f635af (2020-10-29 18:09:19 -0400)
registy: add apply and delete
> registy: add apply and delete

- examples/kind.yaml
- pkg/api/types.go
- pkg/cluster/admin.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry:
d862407620f415e824fa11bfab15cb1508481dc9 (2020-10-30 19:16:23 -0400)
cluster: can create kind clusters with registries
> cluster: can create kind clusters with registries

- pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/test:
e31f86afaf310de7be639a03b4402eb47ad3acf7 (2020-11-04 16:45:49 -0500)
fix unit tests on macos
> fix unit tests on macos

- .circleci/config.yml
- .goreleaser.yml
- cmd/ctlptl/main.go
Hello @nicks,
Please review the following commits I made in branch nicks/release:
a845701ddfdac90ef112039bceff1e24d66503bc (2020-11-04 18:00:46 -0500)
add release scripts for ctlptl
> add release scripts for ctlptl

- .circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/circleci:
aec08eee23bb5f77c63204a00cfef5fa50bd2519 (2020-11-04 18:27:18 -0500)
tweak the release trigger
> tweak the release trigger

- pkg/cluster/docker_for_mac.go
- pkg/cmd/docker_desktop.go
- pkg/cmd/root.go
Hello @nicks,
Please review the following commits I made in branch nicks/docker-desktop:
607601d234408935696b9482faec0c79350df1d5 (2020-11-05 18:25:44 -0500)
add docker-desktop command
> add docker-desktop command

- pkg/cluster/docker_for_mac.go
- pkg/cluster/docker_for_mac_test.go
- pkg/cmd/docker_desktop.go
Hello @nicks,
Please review the following commits I made in branch nicks/docker-desktop:
ea3bee8ec83910f39e26d04ebfa583cb1d549895 (2020-11-05 21:46:34 -0500)
add docker-desktop set command
> add docker-desktop set command

- go.mod
- go.sum
- pkg/cluster/admin.go
- pkg/cluster/cluster_test.go
- pkg/cluster/docker_desktop.go
- pkg/cluster/docker_desktop_dial.go
- pkg/cluster/docker_desktop_dial_windows.go
- pkg/cluster/docker_desktop_test.go
- pkg/cluster/machine.go
- pkg/cmd/docker_desktop.go
Hello @nicks,
Please review the following commits I made in branch nicks/windows:
b0d24a8758958e84a313e379722b587eb92fa98b (2020-11-06 10:55:49 -0500)
windows support
> windows support

- examples/kind.yaml
- examples/minikube.yaml
- go.sum
- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/admin_minikube.go
- pkg/cluster/cluster.go
- pkg/cluster/machine.go
Hello @nicks,
Please review the following commits I made in branch nicks/minikube:
bbebd3409c661fd8f0f31f3e69c5ec41bbcab11f (2020-11-06 15:23:59 -0500)
add minikube support
> add minikube support

- .circleci/config.yml
- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme:
370d2ef5bdd808afca8d779ac9c1bd3226a99910 (2020-11-06 15:44:17 -0500)
flesh out the readme
> flesh out the readme

- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme2:
458e887976bf02f21ea44c4f5619dc719955e444 (2020-11-06 18:44:23 -0500)
add linkable headers
> add linkable headers

- go.mod
- go.sum
Hello @nicks,
Please review the following commits I made in branch nicks/wmclient:
a7cfdb404b70ef72661960698fbacf702b8b72f9 (2020-11-09 12:50:10 -0500)
upgrade wmclient
> upgrade wmclient

- examples/minikube-k8s-14.yaml
- go.sum
- pkg/api/types.go
- pkg/cluster/admin_minikube.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cmd/get.go
Hello @nicks,
Please review the following commits I made in branch nicks/kversion:
3ba575d45f0df859dbcc4f38976a9f30e6272015 (2020-11-11 18:35:43 -0500)
cluster: add spec for setting kubernetes version
> cluster: add spec for setting kubernetes version

- test/simple-server/main.go
Hello @nicks,
Please review the following commits I made in branch nicks/simple-server:
5a9d6da49ae14fa46643b707b2b0fd65001ab269 (2020-11-15 22:48:28 -0500)
add a simple server for testing
> add a simple server for testing

- pkg/cmd/apply.go
Hello @nicks,
Please review the following commits I made in branch nicks/order:
3f6c07a81a6d5dfdce305c4de358db50541e1192 (2020-11-16 22:36:48 -0500)
cmd: apply registries first
> cmd: apply registries first

- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/current:
d8c35949242cba6993bd5f979cb634ae154a62b0 (2020-11-16 23:47:17 -0500)
cluster: add a Current() api
> cluster: add a Current() api

- pkg/cluster/cluster_test.go
- pkg/cluster/docker_desktop.go
- pkg/cluster/machine.go
- pkg/cmd/docker_desktop.go
Hello @nicks,
Please review the following commits I made in branch nicks/quit:
7336badc5f148fbe32745a11849232a87bb32a39 (2020-11-18 18:56:22 -0500)
cmd: add ctlptl docker-desktop quit
> cmd: add ctlptl docker-desktop quit

- pkg/cluster/admin_kind.go
- pkg/cmd/apply.go
- pkg/cmd/create.go
- pkg/cmd/create_cluster.go
- pkg/cmd/create_cluster_test.go
- pkg/cmd/create_registry.go
- pkg/cmd/create_registry_test.go
- pkg/cmd/root.go
Hello @nicks,
Please review the following commits I made in branch nicks/create:
e7b6f372ee50c52adb956aad7906cbe7f8f9f8dc (2020-11-18 20:10:28 -0500)
cmd: add ctlptl create cluster, ctlptl create registry
> cmd: add ctlptl create cluster, ctlptl create registry

- README.md
Signed-off-by: aisuko <urakiny@gmail.com>
The PR fixes issue #64
> Fix the k3d repo's links and and manually install

- pkg/cluster/docker_desktop.go
- pkg/cluster/docker_desktop_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/desktop:
b0157bdeb0bc450930eca09b47d3519b47815697 (2020-12-07 13:00:20 -0500)
cluster: improve error reporting for docker-desktop settings. Fixes https://github.com/tilt-dev/ctlptl/issues/71
> cluster: improve error reporting for docker-desktop settings. Fixes https://github.com/tilt-dev/ctlptl/issues/71

- examples/kind_custom_config.yaml
- go.mod
- go.sum
- pkg/cluster/admin_kind.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/cmp:
6c6dbfc5d45ea3c77c69e57c3676b1701791bd4d (2020-12-08 23:44:10 -0500)
cluster: delete and re-create the cluster when the config changes
> cluster: delete and re-create the cluster when the config changes

- .gitignore
- Makefile
- pkg/api/types.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cmd/create_cluster_test.go
- pkg/cmd/create_registry_test.go
- pkg/cmd/delete_test.go
- pkg/cmd/get_test.go
- pkg/registry/registry.go
Signed-off-by: aisuko <urakiny@gmail.com>
Signed off: yes
fixes: #82
> Add golangci-lint and fix the issues

- .circleci/config.yml
- cmd/ctlptl/main.go
- pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/fixups:
811f5373528061390c5a5971975a925894838a09 (2020-12-17 10:13:06 -0500)
ci: add golangci-lint to circleci
> ci: add golangci-lint to circleci

- pkg/cluster/cluster.go
Hello @nicks,
Please review the following commits I made in branch nicks/issue87:
3fe9f7c9e02039d733b8d0d8a5cd52cf61f37086 (2021-01-11 12:17:22 -0500)
cluster: add more cluster checks for minikube initialization. Fixes https://github.com/tilt-dev/ctlptl/issues/87
> cluster: add more cluster checks for minikube initialization. Fixes https://github.com/tilt-dev/ctlptl/issues/87

- pkg/cluster/admin_kind.go
- pkg/cluster/admin_kind_test.go
https://github.com/kubernetes-sigs/kind/releases/tag/v0.10.0
> ctlptl: add kindest/node tags for kind 0.10.0

- README.md
Hello @ellenkorbes,
Please review the following commits I made in branch nicks/readme:
b6e8dc03f2deeba641063ddcac0dc4181e15f273 (2021-02-02 13:13:41 -0500)
docs: add notes about installing cluster
> docs: add notes about installing cluster

- INSTALL.md
- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/release:
f067a6aa2545fa017b99772be0d021f609ee988a (2021-03-16 14:29:12 -0400)
add an installation appendix. Fixes https://github.com/tilt-dev/ctlptl/issues/75
> add an installation appendix. Fixes https://github.com/tilt-dev/ctlptl/issues/75

- .circleci/config.yml
- .goreleaser.yml
- hack/Dockerfile
Hello @nicks,
Please review the following commits I made in branch nicks/docker:
202eff59a8f98ed8f624bc72726d9f6f18110c2d (2021-03-16 14:40:52 -0400)
goreleaser: add a release docker image
> goreleaser: add a release docker image

- INSTALL.md
- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/update:
387377d0acbf79b40d1b5d0b6070e9449f418fe1 (2021-03-16 15:42:31 -0400)
readme: add new features to readme
> readme: add new features to readme

- pkg/cluster/docker_desktop.go
- pkg/cluster/docker_desktop_test.go
Please review the following commits I made in branch nicks/issue105:
b56038da7f92f0543d77243b729ae2df414595e3 (2021-04-07 20:31:58 -0400)
cluster: update docker-desktop client for new docker protocol. Fixes issue #105
> cluster: update docker-desktop client for new docker protocol. Fixes issue #105

- .circleci/config.yml
- CONTRIBUTING.md
- cmd/ctlptl/main.go
Hi,
I fixed the default branch name throughout the codebase.
> replace master mentions with main

- .circleci/Dockerfile
- .circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/updates:
678e8517e277e48f956504364973e89b6f007d3f (2021-06-07 11:33:27 -0400)
circleci: update docker,kind
> circleci: update docker,kind

- go.mod
- go.sum
- pkg/cluster/cluster.go
Hello @nicks,
Please review the following commits I made in branch nicks/timeout:
7d4c8f9477d0b2039402671f239f4985ef09ee5e (2021-06-11 19:36:23 -0400)
cluster: fetch cluster info in parallel and add reasonable timeouts.
Fixes https://github.com/tilt-dev/ctlptl/issues/113
> cluster: fetch cluster info in parallel and add reasonable timeouts.

- internal/socat/socat.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/issue115:
83331fbdedd90ec6030ff23d09f99adaeefb6838 (2021-06-11 20:08:30 -0400)
cluster: refine check for local docker host
> cluster: refine check for local docker host

- pkg/cluster/docker_desktop.go
Hello @nicks,
Please review the following commits I made in branch nicks/issue117:
925c0b702acbed4428ed392c4f01977c61695ac7 (2021-06-11 20:39:59 -0400)
cluster: improve error messages on docker-desktop client
> cluster: improve error messages on docker-desktop client

- .circleci/config.yml
- hack/release-update-install.sh
- hack/release.sh
Hello @nicks,
Please review the following commits I made in branch nicks/updatereadme:
c58b68055fe65180f3533dd2f716ffe07bf9c344 (2021-09-23 12:15:57 -0400)
hack: auto-update install instructions
> hack: auto-update install instructions

- hack/release-update-install.sh
Hello @nicks,
Please review the following commits I made in branch nicks/updatereadme:
3d1e22bb8341d48ab284526d68284cfaa0f2a1c0 (2021-09-23 12:27:59 -0400)
uncomment part that actually commits :joy:
c58b68055fe65180f3533dd2f716ffe07bf9c344 (2021-09-23 12:15:57 -0400)
hack: auto-update install instructions
> uncomment part that actually commits :joy:

- pkg/cluster/product.go
- pkg/cluster/product_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/rancherdesktop:
980f0f4fd0090a556ac73d3bbc4d14551e690b9a (2021-09-28 15:47:01 -0400)
cluster: add rancher, k3d detection
> cluster: add rancher, k3d detection

- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/docker.go
- pkg/cluster/machine.go
- pkg/docker/docker.go
- pkg/docker/docker_test.go
- pkg/registry/registry.go
Hello @nicks,
Please review the following commits I made in branch nicks/remote:
4166065f3e5b2482f7f5fee1153a9178d6e88689 (2021-09-28 16:50:19 -0400)
cluster: improve local docker host detection
> cluster: improve local docker host detection

- hack/release-update-install.sh
- hack/release.sh
Hello @nicks,
Please review the following commits I made in branch nicks/update3:
3ae107d8049fcf937e32b5f445259f41dcded38e (2021-09-28 20:48:46 -0400)
update release script
> update release script

- pkg/cluster/cluster.go
Hello @nicks,
Please review the following commits I made in branch nicks/socat:
d24bbc77906a2d8e2534c1eb2381a29c5e5af827 (2021-10-07 20:24:19 -0400)
cluster: recreate socat tunnels if they die
> cluster: recreate socat tunnels if they die

- hack/release-update-docs.sh
Hello @nicks,
Please review the following commits I made in branch nicks/releaser:
e834d33894fcb4c731ef37a8004a75781bd24ea8 (2021-12-10 15:55:40 -0500)
hack: minor update to release bot
> hack: minor update to release bot

- .circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/goreleaser3:
4c68d99d8da99b24795ea25fbd7722d7b1749f71 (2021-12-22 19:14:58 -0500)
circleci: install goreleaser with go
> circleci: install goreleaser with go

- .goreleaser.yml
Hello @nicks,
Please review the following commits I made in branch nicks/completion:
018df7534f8f8cc1345d42608313c2536b490e7b (2021-12-22 19:03:28 -0500)
goreleaser: install bash completion
> goreleaser: install bash completion

- go.mod
- go.sum
Hello @nicks,
Please review the following commits I made in branch nicks/deps:
b41eeefec4343e684a91a78bcd06762edb3acd21 (2021-12-23 12:27:15 -0500)
deps: upgrade docker dependencies
> deps: upgrade docker dependencies

- pkg/registry/registry.go
- pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/preserve:
047bffc30df9ce3df4de29391885a4ac0776ced4 (2021-12-23 17:04:39 -0500)
registry: preserve existing labels/ports when re-creating a registry
> registry: preserve existing labels/ports when re-creating a registry

- pkg/registry/registry.go
- pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry5:
37e924bba3ff1a4e0681ed75ab7134ad81836dea (2021-12-23 18:04:16 -0500)
registry: fix a bug in label application
> registry: fix a bug in label application

- test/kind-cluster-network/builder.yaml
- test/kind-cluster-network/e2e.sh
- test/kind-cluster-network/simple-server.yaml
- test/minikube-cluster-network/builder.yaml
- test/minikube-cluster-network/e2e.sh
- test/minikube-cluster-network/simple-server.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/e2e:
df124451c85f79807a6ff613eea6e6dad4f4145d (2022-01-03 19:09:47 -0500)
test: improve paramaterization of test yaml
> test: improve paramaterization of test yaml

- .circleci/config.yml
- test/kind-cluster-network/cluster.yaml
- test/kind-cluster-network/e2e.sh
- test/minikube-cluster-network/cluster.yaml
- test/minikube-cluster-network/e2e.sh
Hello @nicks,
Please review the following commits I made in branch nicks/upgrades:
99c6960ce5ffdad383bceb6382d10c5602febc71 (2022-01-04 10:53:22 -0500)
test: upgrade deps
> test: upgrade deps

- examples/k3d.yaml
- pkg/cluster/admin_k3d.go
- pkg/cluster/cluster.go
- pkg/cluster/product.go
- test/e2e.sh
- test/k3d-cluster-network/Dockerfile
- test/k3d-cluster-network/builder.yaml
- test/k3d-cluster-network/cluster.yaml
- test/k3d-cluster-network/e2e.sh
- test/k3d-cluster-network/registry.yaml
- test/k3d-cluster-network/simple-server.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/k3d:
efbb954ecf5cf2228e0b1ba307ec45746a04b584 (2022-01-03 19:31:26 -0500)
cluster: add support for k3d
> cluster: add support for k3d

- .circleci/Dockerfile
- hack/Dockerfile
Hello @nicks,
Please review the following commits I made in branch nicks/version:
3eaf43ef13aec7560912dccae8912936f1627d5c (2022-01-07 16:29:54 -0500)
hack: upgrade docker client version
> hack: upgrade docker client version

- pkg/cluster/admin_minikube.go
Hello @lizzthabet, @milas,
Please review the following commits I made in branch nicks/issue144:
03d031c3d8367d938bc6b80fa225c0bc9b9548e2 (2022-01-18 17:22:44 -0500)
cluster: disconnect the registry before starting minikube, to prevent ip clashes
fixes https://github.com/tilt-dev/ctlptl/issues/144
> cluster: disconnect the registry before starting minikube, to prevent ip clashes

- .circleci/config.yml
- pkg/cluster/admin_minikube.go
#182 plus bump of Minikube version for testing
> Test #182 with Minikube 1.25

- pkg/cluster/docker_desktop_dial_windows.go
Please review the following commits I made in branch nicks/windows2:
01e22d885c99d6601bc38a5a5c2e4b31bb9084de (2022-01-26 16:57:45 -0500)
cluster: adjust connection settings for docker-desktop 4.4.4
> cluster: adjust connection settings for docker-desktop 4.4.4

- .circleci/Dockerfile
- .circleci/config.yml
- hack/Dockerfile
- pkg/cluster/admin_kind.go
- test/kind-cluster-network/e2e.sh
Hello @nicks,
Please review the following commits I made in branch nicks/bump:
efd487e4f4e9b28bf33f4672b54f96efd0625b89 (2022-03-07 12:23:33 -0500)
cluster: bump kind version
> cluster: bump kind version

- .goreleaser.yml
Hello @nicks,
Please review the following commits I made in branch nicks/releaser:
465f4530bb96298fedee3c1bf03ddf7fb8536744 (2022-03-07 13:13:36 -0500)
release: update changelog to include github handles
> release: update changelog to include github handles

- pkg/cmd/analytics.go
Hello @nicks,
Please review the following commits I made in branch nicks/logger:
fd54de6d6bcea7263027d54af71a4fba20d2f6d3 (2022-03-28 14:52:15 -0400)
cmd: turn off the analytics logger
> cmd: turn off the analytics logger

- pkg/cluster/admin_minikube.go
Hello @milas, @lizzthabet,
Please review the following commits I made in branch nicks/hosting:
20218090571b623ff455072bfdf4e6e54fadb0a3 (2022-04-15 19:41:20 -0400)
cluster: don't use registry mirroring on minikube
Fixes https://github.com/tilt-dev/ctlptl/issues/180
This changes the local-registry-hosting config so that,
instead of pushing and pulling from the same URL (localhost:5000),
we'll push to localhost:5000 and pull from [registry-name]:5000.
To maximize compatibility, we'll still add the registry mirroring
to the containerd.toml. But because minikube doesn't do a good job
preserving the toml across stop/start, the local-registry-hosting
config will tell tilt not to use this feature.
* Code is …
> cluster: don't use registry mirroring on minikube

- Makefile
- internal/printers/name.go
- internal/socat/socat.go
- pkg/cluster/admin.go
- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/admin_minikube.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/docker.go
- pkg/cluster/docker_desktop_dial.go
- pkg/cluster/docker_desktop_dial_windows.go
- pkg/cluster/machine.go
- pkg/cluster/options.go
- pkg/cmd/apply.go
- pkg/cmd/create_cluster.go
- pkg/cmd/create_cluster_test.go
- pkg/cmd/create_registry.go
- pkg/cmd/create_registry_test.go
- pkg/cmd/delete.go
- pkg/cmd/docker_desktop.go
- pkg/cmd/get.go
- pkg/cmd/get_test.go
- pkg/cmd/printer.go
- pkg/cmd/socat.go
- pkg/encoding/encoding.go
- pkg/encoding/encoding_test.go
- pkg/registry/options.go
- pkg/registry/registry_test.go
- pkg/visitor/decode.go
(This is silly but I was fighting my editor while working on the codebase today)
> lint: add fmt task to Makefile

- pkg/cmd/delete.go
Hello @nicks,
Please review the following commits I made in branch nicks/del:
70e4cd5a10224b4a73fca830c44c097f1c79e11e (2022-04-26 16:25:57 -0400)
cmd: 'ctlptl delete cluster kind' and 'ctlptl delete cluster k3d' should delete the default cluster
> cmd: 'ctlptl delete cluster kind' and 'ctlptl delete cluster k3d' should delete the default cluster

- .circleci/Dockerfile
- .circleci/config.yml
- hack/Dockerfile
- pkg/cluster/admin_kind.go
- test/kind-cluster-network/e2e.sh
Hello @nicks,
Please review the following commits I made in branch nicks/kind13:
a0f0175844eaa096c94672d86c494d4d81e24ac2 (2022-05-10 17:47:19 -0400)
cluster: updates for kind 1.13
> cluster: updates for kind 1.13

- .circleci/Dockerfile
- .circleci/config.yml
- go.mod
- go.sum
- hack/Dockerfile
- pkg/cluster/admin_kind.go
Hello @nicks,
Please review the following commits I made in branch nicks/kind2:
ac817c40da86ae28df9b4920b035dc33e900ac2b (2022-05-20 11:34:25 -0400)
cluster: update kind to v0.14.0
> cluster: update kind to v0.14.0

- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/docker_desktop.go
- pkg/cluster/docker_desktop_dial.go
- pkg/cmd/docker_desktop.go
- pkg/docker/docker.go
Taking a stab at DD for linux. I don't have a working DD for linux I can use yet, so I'd appreciate anyone who could build and try this!
- chore: changes from `make fmt`
- cluster: add docker desktop for linux support
> Docker Desktop for Linux support

- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/cluster/machine.go
- pkg/docker/docker.go
- pkg/docker/docker_test.go
Please review the following commits I made in branch nicks/d4l:
0d117d1ce4ef3bf6806715556d179b47c420fba9 (2022-06-16 17:14:16 -0400)
cluster: more docker desktop linux fixes
> cluster: more docker desktop linux fixes

- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
@milas does this solve the issue for you?
Fixes #232.
> dockerdesktop: reset cluster on create, not delete

- NOTICE
- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme:
616e83e39ab8b29345fdf2b23ff927a90fd741b2 (2022-06-23 17:55:07 -0400)
update readme to reflect docker acquisition
> update readme to reflect docker acquisition

- pkg/cluster/admin_kind.go
Hello tilt-dev's team,
Can we override docker network using environment var : KIND_EXPERIMENTAL_DOCKER_NETWORK just like it's possible in kind ?
cf. https://github.com/kubernetes-sigs/kind/blob/64b1432242dd788a2ca1ca4d47a14bbe2067be40/pkg/cluster/internal/providers/docker/provider.go#L72-L77
It's an experimental feature but it leaves users with complex networking desires to create and manage their own networks.
> Overriding docker network due to KIND_EXPERIMENTAL_DOCKER_NETWORK

- README.md
- pkg/cmd/docker_desktop.go
Hello @milas, @nicksieger,
Please review the following commits I made in branch nicks/k8s:
1d91b17c902cb5bc05ee314e2840fede03a75c6e (2022-07-28 15:16:27 -0400)
cmd: add docker-desktop disable kubernetes to the list of examples
> cmd: add docker-desktop disable kubernetes to the list of examples

- internal/dctr/run.go
- pkg/cluster/cluster.go
Hello @nicks,
Please review the following commits I made in branch nicks/ioutil:
527f8d42385ef352f566b811eddd758686b9af09 (2022-08-11 18:39:27 -0400)
clean up deprecated ioutil functions
> clean up deprecated ioutil functions

- pkg/cluster/docker_desktop.go
- pkg/cluster/docker_desktop_test.go
Effective Docker Desktop version 4.12.
> cluster: settings endpoint moved to backend /app/settings

- .circleci/Dockerfile
- .circleci/config.yml
- Makefile
- hack/Dockerfile
- pkg/cluster/admin_kind.go
- test/kind-cluster-network/e2e.sh
> cluster: update node images for kind v0.16

- pkg/cluster/admin_kind.go
Please review the following commits I made in branch nicks/already:
ce301eb8bf67e7cf85dd4e105be043b4f72865f7 (2022-10-18 16:24:29 -0400)
clusters: delete orphaned kind clusters
> clusters: delete orphaned kind clusters

- .circleci/Dockerfile
- .circleci/config.yml
- hack/Dockerfile
- pkg/cluster/admin_kind.go
> kind: update to Kind v0.17

- .circleci/config.yml
- .goreleaser.yml
- Makefile
> ci: build releases based on golang:1.19-bullseye

- test/docker-desktop/Dockerfile
- test/docker-desktop/builder.yaml
- test/docker-desktop/cluster.yaml
- test/docker-desktop/e2e.sh
- test/docker-desktop/simple-server.yaml
these only run locally because i haven't figured out how to run DD on ci yet
> test: add docker-desktop k8s tests

- internal/dctr/run.go
Some bits of the load sequence changed in Docker 24
This code has been copied from
https://github.com/tilt-dev/tilt/pull/6191
sadly, it's a PITA to test, because Docker loads the env variables at startup
> dctr: adjust how CLI is loaded

- pkg/cluster/admin_kind.go
- pkg/cluster/admin_kind_test.go
- pkg/cluster/cluster.go
this is just refactoring to make the next couple changes easier
> cluster: update kind admin to use our abstract RunIO interface

- pkg/api/types.go
- pkg/cluster/admin.go
- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/admin_kind.go
- pkg/cluster/admin_kind_test.go
- pkg/cluster/admin_minikube.go
- pkg/cluster/docker.go
This reverts commit 5d03bf0f1720a3448f745cc2cb338ecdce58854e.
> Revert "cluster: update kind to use new containerd patch format (#314)"

- pkg/api/types.go
- pkg/cluster/admin.go
- pkg/cluster/admin_docker_desktop.go
- pkg/cluster/admin_kind.go
- pkg/cluster/admin_kind_test.go
- pkg/cluster/admin_minikube.go
- pkg/cluster/docker.go
- test/k3d/e2e.sh
- test/kind/e2e.sh
- test/minikube/e2e.sh
try again!
we need two registry redirects:
- one to redirect http://localhost:12345 to http://my-registry:5000
- one to redirect https://my-registry:5000 to http://my-registry:5000
> cluster: update kind to use new containerd patch format

- .goreleaser.yml
> goreleaser: fix deprecations

- .circleci/Dockerfile
- .circleci/config.yml
- go.mod
- go.sum
- pkg/cluster/admin_kind.go
- test/kind/cluster.yaml
- test/kind/e2e.sh
based on https://github.com/tilt-dev/ctlptl/pull/339
> cluster: add support for kind v0.23.0

- go.mod
- go.sum
- pkg/cluster/docker.go
fixes some otel vendoring madness
fixes https://github.com/tilt-dev/ctlptl/issues/350
> vendor: docker v27

- .circleci/Dockerfile
- .circleci/config.yml
- .goreleaser.yml
- Makefile
- go.mod
- pkg/cluster/docker_desktop_dial.go
> circleci: update goreleaser

- .circleci/config.yml
- test/docker-desktop/Dockerfile
- test/k3d/Dockerfile
- test/kind/Dockerfile
- test/minikube/Dockerfile
- test/minikube/cluster.yaml
- test/minikube/e2e.sh
> test: use go 1.23 in e2e tests

- .circleci/Dockerfile
- .circleci/config.yml
- hack/Dockerfile
- pkg/cluster/admin_kind.go
- test/kind/e2e.sh
> cluster: update to kind 1.25

- .circleci/Dockerfile
- .circleci/config.yml
- hack/Dockerfile
- pkg/cluster/admin_kind.go
- test/kind/e2e.sh
> cluster: update to kind 1.26

- Makefile
- hack/publish-ci-image.sh
> makefile: add automation around updating the circleci image

- .circleci/Dockerfile
- .circleci/config.yml
- Makefile
- go.mod
- test/docker-desktop/Dockerfile
- test/k3d/Dockerfile
- test/kind/Dockerfile
- test/minikube/Dockerfile
> golang: update to 1.24

- pkg/api/k3dv1alpha5/types.go
just re-copied this,
i assume this was added after we plugged it into ctlptl
fixes https://github.com/tilt-dev/ctlptl/issues/379
> k3d: update v1alpha5 api

- .circleci/config.yml
- .golangci.yaml
- Makefile
- internal/dctr/run.go
- pkg/cluster/admin_helpers.go
- pkg/cluster/admin_kind.go
- pkg/cluster/admin_kind_test.go
- pkg/cluster/admin_minikube.go
- pkg/cluster/docker_desktop.go
- pkg/cluster/machine.go
- pkg/cmd/apply.go
- pkg/cmd/create_cluster.go
- pkg/cmd/create_registry.go
- pkg/cmd/delete.go
- pkg/cmd/get.go
- pkg/visitor/decode.go
> deps: update golangci-lint

- .circleci/Dockerfile
- .circleci/config.yml
- go.mod
- go.sum
- hack/Dockerfile
- pkg/cluster/admin_kind.go
> cluster: add kind29 support

- .circleci/Dockerfile
- .circleci/config.yml
- go.mod
- go.sum
- hack/Dockerfile
- pkg/cluster/admin_kind.go
- test/kind/cluster.yaml
- test/kind/e2e.sh
> vendor: updates for kind v0.30
