pkg/cmd/get.go
Hello @nicks,
Please review the following commits I made in branch nicks/init:
37b12e2623044556f47b2257d433110a8f8fa750 (2020-10-19 18:55:54 -0400)
ctlptl get should default to clusters
=> ctlptl get should default to clusters

pkg/cmd/get.go, pkg/registry/options.go, pkg/registry/registry.go, pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry:
908e74cf62125f05ee15b55e76ce78701a95bf7e (2020-10-23 18:50:30 -0400)
registry: add a registry controller for listing the registries
=> registry: add a registry controller for listing the registries

go.mod, go.sum, pkg/registry/registry.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry2:
8ec742f9c541b23dad98f3df448ee088cd00b58c (2020-10-30 11:39:29 -0400)
registry: don't use 0 in the port spec, because that causes docker to randomly re-assign the port
=> registry: don't use 0 in the port spec, because that causes docker to randomly re-assign the port

go.mod, pkg/cluster/admin.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/registry/options.go, pkg/registry/registry.go, pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/registry3:
0e87d1ef78fa6e9afddba16d65f6fbcc96ed0b01 (2020-10-30 22:51:05 -0400)
cluster: more robust linkage between cluster and registry
=> cluster: more robust linkage between cluster and registry

Makefile, pkg/cluster/admin.go, pkg/cluster/cluster_test.go, pkg/cluster/docker_for_mac.go, pkg/cluster/docker_for_mac_test.go, pkg/cluster/machine.go
Hello @nicks,
Please review the following commits I made in branch nicks/d4m-delete:
3d029d3e7ba28b4848c098fc28f60873feeaef58 (2020-11-04 17:03:35 -0500)
cluster: support deletion of a docker-desktop-based cluster
=> cluster: support deletion of a docker-desktop-based cluster

README.md
Please review the following commits I made in branch nicks/install:
a8427bff8a304b0862064f349a4f59a879ee8b01 (2020-11-05 12:20:17 -0500)
readme: add docs
=> readme: add docs

cmd/ctlptl/main.go
Hello @nicks,
Please review the following commits I made in branch nicks/flags:
0b3efcd040cc6ebb2939f5a3030fa3e06702bf21 (2020-11-05 21:51:38 -0500)
hide klog flags from the help output
=> hide klog flags from the help output

pkg/api/types.go, pkg/cluster/cluster.go, pkg/cmd/get.go, pkg/cmd/get_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/current:
7ae93eaf468c9f0485f5dd67a02a3dbe2fbea049 (2020-11-09 13:03:42 -0500)
cluster: print current cluster, like kubectl config get-contexts
=> cluster: print current cluster, like kubectl config get-contexts

pkg/cluster/admin_docker_desktop.go, pkg/cluster/cluster_test.go, pkg/cluster/docker_desktop.go, pkg/cluster/machine.go, pkg/cmd/docker_desktop.go
Hello @nicks,
Please review the following commits I made in branch nicks/reset:
d5f48190a59fa0dcf935ab9c7e200f1f059af205 (2020-11-13 13:28:37 -0500)
cmd: add a docker-desktop reset-cluster command
=> cmd: add a docker-desktop reset-cluster command

pkg/cluster/admin_minikube.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/docker.go, pkg/cluster/machine.go
Hello @nicks,
Please review the following commits I made in branch nicks/minikube-network:
fd978210d5b66c11b26938a6144aa95779cee710 (2020-11-16 20:39:30 -0500)
cluster: minikube 1.15 creates a unique network for each cluster
=> cluster: minikube 1.15 creates a unique network for each cluster

pkg/cluster/admin.go, pkg/cluster/admin_docker_desktop.go, pkg/cluster/admin_kind.go, pkg/cluster/admin_minikube.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/minikube-network2:
d00237a587f1490de0c0d0553f3fb120457b6227 (2020-11-16 21:10:42 -0500)
cluster: add HostFromClusterNetwork to minikube
=> cluster: add HostFromClusterNetwork to minikube

.circleci/config.yml, Makefile, pkg/cluster/admin_kind.go, pkg/cluster/admin_minikube.go, test/e2e.sh, test/kind-cluster-network/Dockerfile, test/kind-cluster-network/builder.yaml, test/kind-cluster-network/cluster.yaml, test/kind-cluster-network/e2e.sh, test/kind-cluster-network/registry.yaml, test/kind-cluster-network/simple-server.yaml, test/minikube-cluster-network/Dockerfile, test/minikube-cluster-network/builder.yaml, test/minikube-cluster-network/cluster.yaml, test/minikube-cluster-network/e2e.sh, test/minikube-cluster-network/registry.yaml, test/minikube-cluster-network/simple-server.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/issue49:
43876ab14c1ff7dd369a6b3ef127d096682b2ccf (2020-11-16 17:56:29 -0500)
cluster: add registry mirrors for the cluster network
Fixes https://github.com/tilt-dev/ctlptl/issues/49
2a0b38598dca453eb7c46286e69b997fe736ed80 (2020-11-15 22:45:29 -0500)
fix
=> cluster: add registry mirrors for the cluster network

.goreleaser.yml
Hello @nicks,
Please review the following commits I made in branch nicks/goreleaser:
ae3b4a46598d17e577c843aece1d74c4e6cc5fcb (2020-11-18 09:54:12 -0500)
release: update goreleaser to use https
=> release: update goreleaser to use https

pkg/cluster/admin_docker_desktop.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/config.go
Hello @nicks,
Please review the following commits I made in branch nicks/contexts:
71cd59843f25e2d363bb7ff52e1c8b9b13ca76a3 (2020-11-18 20:50:18 -0500)
cluster: applying a new cluster should make it the current. deleting a cluster should remove it from kubeconfig
=> cluster: applying a new cluster should make it the current. deleting a cluster should remove it from kubeconfig

.goreleaser.yml
Currently goreleaser is setup with the wrong url resulting in 404 within scoop, this should hopefully fix that, thanks.
=> Fix ctlptl 404

go.mod, go.sum, pkg/cluster/admin_kind.go, pkg/cluster/admin_kind_test.go, pkg/cluster/cluster.go, test/kind-cluster-network/cluster.yaml, test/minikube-cluster-network/cluster.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/kind:
0017c5f2c48001d8603f2b05ea545c9c5b16a45c (2020-12-04 00:53:49 -0500)
cluster: add the ability to load a specific kubernetes version on kind. Fixes https://github.com/tilt-dev/ctlptl/issues/66
=> cluster: add the ability to load a specific kubernetes version on kind. Fixes https://github.com/tilt-dev/ctlptl/issues/66

test/kind-cluster-network/cluster.yaml, test/kind-cluster-network/e2e.sh, test/minikube-cluster-network/cluster.yaml, test/minikube-cluster-network/e2e.sh
Hello @nicks,
Please review the following commits I made in branch nicks/versiontest:
adc57e15fb0f457844bf450324edab488985ae58 (2020-12-04 01:11:14 -0500)
test: add e2e tests for setting kubernetes version
=> test: add e2e tests for setting kubernetes version

README.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme:
a31de53a61759ffcc3c8e7390fa3f557c09ee1bc (2020-12-04 01:28:17 -0500)
add an example of setting the kuberentes version to the docs
=> add an example of setting the kuberentes version to the docs

examples/kind_custom_config.yaml, pkg/cluster/cluster.go
Hello @nicks,
Please review the following commits I made in branch nicks/configmap:
7dd444fadbccf9fc1af7318dbdb14f1f41dc0160 (2020-12-08 12:26:09 -0500)
cluster: store the cluster spec in the cluster itself
=> cluster: store the cluster spec in the cluster itself

pkg/cluster/config.go
Hello @nicks,
Please review the following commits I made in branch nicks/apply:
7c9d6db48a96d3025c6382c582f2e4f219bf000d (2020-12-08 13:07:11 -0500)
cluster: make ctlptl apply set the current context
=> cluster: make ctlptl apply set the current context

pkg/cluster/cluster.go
Hello @nicks,
Please review the following commits I made in branch nicks/ports:
98d58ee5be54768cefe3097516f40a9e7bf56fb5 (2020-12-08 19:27:46 -0500)
cluster: print the location of the registry on setup
=> cluster: print the location of the registry on setup

.circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/ci:
b36317f4912dfd6b7948e1d597a2c9c5cd5b6b83 (2020-12-17 09:56:39 -0500)
circleci: don't use contexts on the normal build pipeline
this prevents circleci from running contributor PRs
There's a better way to configure slack for this that doesn't
require contexts
=> circleci: don't use contexts on the normal build pipeline

CONTRIBUTING.md, README.md
Hello @nicks,
Please review the following commits I made in branch nicks/contributing:
56139d459144c103eb246e91d42e7d43e2b11402 (2021-01-11 12:35:57 -0500)
docs: add a contributing guide
=> docs: add a contributing guide

internal/socat/socat.go, pkg/cmd/root.go, pkg/cmd/socat.go
Please review the following commits I made in branch nicks/issue92:
37e5b9c8018d2968251765a1ddeddebf0f535274 (2021-01-29 13:01:25 -0500)
socat: add a utility to forward ports to a remote docker server
=> socat: add a utility to forward ports to a remote docker server

.circleci/Dockerfile, .circleci/config.yml, hack/Dockerfile, pkg/cluster/admin_kind.go, test/kind-cluster-network/cluster.yaml, test/kind-cluster-network/e2e.sh, test/minikube-cluster-network/cluster.yaml, test/minikube-cluster-network/e2e.sh
Hello @landism,
Please review the following commits I made in branch nicks/kind11:
48c695ca624a3787b0d0bffb281076f3ddca301a (2021-05-19 19:20:22 -0400)
cluster: support for kind v0.11
updates all scripts to test against kind v0.11
=> cluster: support for kind v0.11

.circleci/Dockerfile, hack/Dockerfile, pkg/cluster/admin_kind.go
Hi,
I added a map of kind node images for v0.11.1 based on the [release notes](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1).
=> cluster: support for kind v0.11.1 (#109)

pkg/cmd/apply.go, pkg/cmd/create.go, pkg/cmd/create_cluster.go, pkg/cmd/create_registry.go, pkg/cmd/delete.go, pkg/cmd/get.go
Hello @nicks,
Please review the following commits I made in branch nicks/issue114:
5284a7689ab2396d026dedcb84530f42f9291276 (2021-06-11 19:43:27 -0400)
cmd: fix 'ctlptl create' segfault and improve i/o handling
Fixes https://github.com/tilt-dev/ctlptl/issues/114
=> cmd: fix 'ctlptl create' segfault and improve i/o handling

pkg/cluster/admin_kind.go
Hello @nicks,
Please review the following commits I made in branch nicks/issue116:
ac18980fbb5cf5ca6342271704231f9cad1e639b (2021-06-11 20:31:08 -0400)
cluster: improve error message around kind/kubernetes release pinning
Fixes https://github.com/tilt-dev/ctlptl/issues/116
=> cluster: improve error message around kind/kubernetes release pinning

INSTALL.md
- `export` is not needed
- `tar` can install `ctlptl` directly to `/usr/local/bin`
=> Simplify command-line install script

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/issue131:
7ac676df4715438e5261016dd6c4d34b8ac42775 (2021-09-23 00:31:12 -0400)
cluster: add healthchecks on cluster creation
fixes https://github.com/tilt-dev/ctlptl/issues/131
=> cluster: add healthchecks on cluster creation

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/update2:
6665ca0f74c16196abdb1dbc96b917c9f6733ee5 (2021-09-28 15:38:06 -0400)
cluster: adjust timeouts to wait 5 minutes for kubernetes to start
fixes https://github.com/tilt-dev/ctlptl/issues/139
bf4e11cb0371e854ef20e4409ac7eba74f67fa37 (2021-09-23 17:04:46 -0400)
update install
=> cluster: adjust timeouts to wait 5 minutes for kubernetes to start

pkg/cluster/admin_minikube.go
Given that ctlptl is only designed for test and development clusters, and uses only one node by default, I believe it is appropriate to increase the max-pods from the default of 110 to 500 (can increase this further if desired). This allows for microservices architectures with a significant number of pods to be tested without running into kubernetes limits. This can be removed once the existing cli/crd allow for passing all minikube customization options (I believe this is tracked in #86). Thanks.
=> Increase default max pods limit in minikube

pkg/cluster/admin_kind.go, pkg/cluster/admin_kind_test.go
The release note says k8s 1.22 and 1.23 images are known to work well
https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> Support Kubernetes 1.22 and 1.23 for kind

pkg/cluster/docker_desktop.go, pkg/cluster/docker_desktop_dial.go, pkg/cluster/docker_desktop_dial_windows.go
Please review the following commits I made in branch nicks/socket:
35d10644e5ef0d5a895e6dc533d9abac652251a6 (2022-01-13 16:56:48 -0500)
cluster: change the docker-desktop socket path
Fixes https://github.com/tilt-dev/ctlptl/issues/176
=> cluster: change the docker-desktop socket path

go.mod, go.sum, internal/socat/socat.go, pkg/cluster/docker.go, pkg/docker/docker.go, pkg/registry/registry.go
This commit pulls in the Docker CLI's connhelper package which provides some
wrapper code for creating a client that can communicate with a Docker instance
over SSH.
The connection helper package is being used by adding a new ClientOpts()
function that will return a slice of client.Opt values appropriate for
connecting to DOCKER_HOST. If DOCKER_HOST is an ssh url, a set of opts built
using connhelper will be returned. If not, a set containing only client.FromEnv
will be returned, preserving the existing behavior of ctlptl.
=> Allow DOCKER_HOST to use the SSH scheme

pkg/cluster/admin_kind.go, pkg/cluster/admin_kind_test.go, pkg/cluster/admin_minikube.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/docker.go
Hello @nicks,
Please review the following commits I made in branch nicks/docker:
a4c971a9ca27d071b108f637ece5f6792bf2b6d9 (2022-03-30 18:54:50 -0400)
docker: use the API instead of a subshell for connecting networks
=> docker: use the API instead of a subshell for connecting networks

pkg/cluster/admin_docker_desktop.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/docker.go, pkg/cluster/machine.go, pkg/docker/docker.go, pkg/docker/docker_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/colima:
28292aa2f77150996fb4e7d488cbce352248f3b5 (2022-03-31 12:59:04 -0400)
docker: split IsLocalHost() into two functions
When callers use this function, they care about two things:
- Whether the docker server is running remotely, so needs port-forwarding.
- Whether the docker server is the Real Docker Engine, which has additional APIs for VMs
This change splits those two use-cases, so that we work properly with colima
and other docker-compatible runtimes.
=> docker: split IsLocalHost() into two functions

internal/dctr/run.go, internal/socat/socat.go, pkg/cluster/cluster_test.go, pkg/cluster/docker.go, pkg/registry/registry.go, pkg/registry/registry_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/dockerclient:
bd8456af429ba21211c97f945e62cefead711abf (2022-04-01 14:58:05 -0400)
docker: use a docker API client instead of a subshell
=> docker: use a docker API client instead of a subshell

internal/exec/exec.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/machine.go
Hello @milas, @lizzthabet,
Please review the following commits I made in branch nicks/issue211:
77ddf27adccba375f873fb811987586521fb7828 (2022-04-18 16:31:19 -0400)
cluster: make ctlptl handle 'minikube stop' and 'minikube pause' correctly
fixes https://github.com/tilt-dev/ctlptl/issues/211
=> cluster: make ctlptl handle 'minikube stop' and 'minikube pause' correctly

pkg/api/types.go, pkg/cmd/create_registry.go, pkg/cmd/get.go, pkg/docker/docker.go, pkg/registry/registry.go, pkg/registry/registry_test.go
The most common use case here is for restricted environments that
don't have access to Docker hub. (That said, IMO it's better to
use the built-in `--registry-mirrors` option in Docker in this
situation.)
Currently, listing registries is currently done by looking for the
the ancestor image of `registry:2`, which won't work when using a
custom image. As a result, a new label is applied to all registries
created by `ctltptl`: `dev.tilt.ctlptl.role=registry`. The label key
uses the reverse DNS convention as suggested by Docker[1].
For both backwards compatibility (and interop with other tools that
create clusters such as `k3d`), we'll still search for registries by
`ancestor` as well. Additionally, the label will _not_ be applied to
any existing `ctlptl`-managed registries unless they're …
=> registry: add support for custom image

hack/make-rules/generated.sh, internal/exec/exec.go, pkg/api/types.go, pkg/api/zz_generated.deepcopy.go, pkg/cluster/admin_minikube.go, pkg/cluster/admin_minikube_test.go, pkg/cluster/cluster.go, pkg/cmd/create_cluster.go
Please review the following commits I made in branch nicks/flags:
edd4876a47991d2f87ccea1f275cd475daf14dd4 (2022-04-20 16:02:16 -0400)
cluster: add minikube-start-flags
fixes https://github.com/tilt-dev/ctlptl/issues/86
=> cluster: add minikube-start-flags

pkg/cluster/cluster.go, pkg/cmd/create_cluster_test.go, pkg/cmd/delete.go, pkg/cmd/delete_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/cascade:
402a7a32590b57ec4c5e8db7310d2d8fd1b68a7f (2022-05-03 12:57:21 -0400)
cmd: add "ctlptl delete --cascade=true" to delete the registry attached to a cluster.
Fixes https://github.com/tilt-dev/ctlptl/issues/103
=> cmd: add "ctlptl delete --cascade=true" to delete the registry attached to a cluster.

pkg/cmd/delete.go, pkg/cmd/get.go, pkg/cmd/normalize.go
Hello @nicks,
Please review the following commits I made in branch nicks/normalize:
ed00bea7a21f5aa8e198de54fdd78870852cea76 (2022-05-03 15:49:40 -0400)
cmd: normalize cluster name.
Now, 'ctlptl get cluster k3d' and 'ctlptl delete cluster k3d' will
work as expected.
=> cmd: normalize cluster name.

.circleci/config.yml, .goreleaser.yml, hack/Dockerfile
Setup circle and goreleaser to build arm docker images via https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/
=> goreleaser: build and release arm64 images

pkg/cluster/admin_minikube_test.go, pkg/cluster/docker_desktop.go, pkg/cluster/docker_desktop_dial.go, pkg/cluster/docker_desktop_dial_windows.go, pkg/cluster/docker_desktop_test.go, pkg/cmd/create_cluster.go, pkg/cmd/delete_test.go, pkg/cmd/normalize.go
Changes backend socket/pipe to use non-native backend. Also some changes from `make fmt`.
After further review, it looks like /settings need to come from the GUI socket but [/kubernetes from the backend](/tilt-dev/ctlptl/pull/228#pullrequestreview-994116271) socket.
=> Fix Docker Desktop Kubernetes Reset

.circleci/config.yml, .goreleaser.yml, Makefile
Please review the following commits I made in branch nicks/images:
40929f3793bacaee073cb34dd0a5c33543454aef (2022-06-10 12:34:45 -0400)
circleci: move images to docker org
=> circleci: move images to docker org

pkg/cmd/delete.go, pkg/cmd/delete_test.go
Please review the following commits I made in branch nicks/issue-243:
757849fc91d721d19254e1b1d38cdf53562c5f3d (2022-07-28 15:14:24 -0400)
cmd: fix a bug in the cascade flag
fixes https://github.com/tilt-dev/ctlptl/issues/243
=> cmd: fix a bug in the cascade flag

.circleci/Dockerfile, .circleci/config.yml, go.mod
Hello @nicks,
Please review the following commits I made in branch nicks/go119:
1e42f416d62a2a6fec082951d7840259a8919511 (2022-08-22 18:23:41 -0400)
upgrade to go 1.19
=> upgrade to go 1.19

pkg/cluster/admin.go, pkg/cluster/admin_kind.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/config.go, pkg/cluster/docker.go
When ctlptl is run in a container, fix the KIND kubeconfig so ctlptl and other
containers can reach the apiserver on the kind network.
Fixes #251.
=> cluster: detect in-container docker and fix KIND kubeconfig

.circleci/config.yml, pkg/cluster/admin_minikube.go
Please review the following commits I made in branch nicks/issue239:
41bf3d94d3cff051e3d1ada4bb12f4c48e980abd (2022-09-16 12:16:28 -0400)
cluster: handle containerd on minikube 1.27
https://github.com/tilt-dev/ctlptl/issues/239
=> cluster: handle containerd on minikube 1.27

pkg/registry/registry.go, pkg/registry/registry_test.go
Please review the following commits I made in branch nicks/issue247:
1f6d5a6d6a1c2acb2873d2088e6edce1838cb2a6 (2022-09-16 14:31:12 -0400)
registry: enable deletion by default
fixes https://github.com/tilt-dev/ctlptl/issues/247
=> registry: enable deletion by default

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
Please review the following commits I made in branch nicks/cluster:
7cb7ff25a8f13f72633b1e195a861f81b14c6445 (2022-10-17 11:57:38 -0400)
cluster: handle missing clusters correctly
=> cluster: handle missing clusters correctly

pkg/cluster/docker_desktop.go, pkg/cluster/docker_desktop_dial.go, pkg/cluster/docker_desktop_dial_windows.go, pkg/cluster/docker_desktop_test.go
also, while i'm here, refactor the protocol negotiation to better express what's happening and match the socket names on disk
fixes https://github.com/tilt-dev/ctlptl/issues/267
=> cluster: fix settings write payload

pkg/cluster/admin_kind.go
kind v0.17 additionally supports Kubernetes v1.26.0 images.
https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> Support Kubernetes v1.26.0 for kind

README.md
At least in my small team, we all agree that `go install` is the easiest way to install command line tools.
=> Add `go install` to README

pkg/api/types.go, pkg/registry/registry.go, pkg/registry/registry_test.go
Acutally it's not possible to manage env vars of container registry.
Please let'me override registry configuration : https://docs.docker.com/registry/configuration/
A use case, inspirated by following post : https://maelvls.dev/docker-proxy-registry-kind/ is to declare a registry as a docker proxy for kind.
---
Create network, proxy and cluster; attach proxy to the network :
```
export KIND_EXPERIMENTAL_DOCKER_NETWORK=cluster
docker network create --scope local --driver bridge --subnet 10.20.0.0/16 --gateway 10.20.0.1 $KIND_EXPERIMENTAL_DOCKER_NETWORK
ctlptl apply -f /dev/stdin <<EOF                                                                                                                          
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: proxy-docker-hub
env:
- …
```
=> Add env property on Registry

pkg/api/types.go, pkg/api/zz_generated.deepcopy.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
i've recently changed how i'm logged into clusters so that i get auto-logged out aggressively. So there's often a bunch of clusters that i have contexts for but where healthchecks will fail. this is ok! but let's report it.
=> cluster: report errors on the status field

internal/dctr/run.go, internal/socat/socat.go, pkg/cluster/admin.go, pkg/cluster/admin_kind.go, pkg/cluster/admin_minikube.go, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/docker.go, pkg/cluster/machine.go, pkg/cmd/socat.go, pkg/registry/registry.go, pkg/registry/registry_test.go
this was mainly a yak shave, since the credentials come from the CLI rather than the API client.
fixes https://github.com/tilt-dev/ctlptl/issues/303
=> docker: pass credentials to image pull

pkg/cluster/admin_helpers.go, pkg/cluster/admin_kind.go, pkg/cluster/admin_minikube.go
they're both configuring the same containerd under the hood, so let's just do them the same way.
=> cluster: unify minikube and kind registry configs

.circleci/Dockerfile, .circleci/config.yml, hack/Dockerfile
looks like the kubernetes repos broke
this installation path, see this thread:
https://forum.linuxfoundation.org/discussion/864693/the-repository-http-apt-kubernetes-io-kubernetes-xenial-release-does-not-have-a-release-file
=> dockerfile: update how we install kubectl, docker clis

pkg/registry/registry.go, pkg/registry/registry_test.go
the old logic wasn't doing the 3-way merge quite right
fixes https://github.com/tilt-dev/ctlptl/issues/344
=> registry: tweak how desired image is reconciled

pkg/cluster/admin_kind.go, pkg/cluster/admin_kind_test.go
when there are multiple control plane nodes,
kind creates an LB node in front of them.
before this change, we would try
to configure the registry on the LB node,
which is unnecessary and doesn't work.
fixes https://github.com/tilt-dev/ctlptl/issues/356
=> kind: fix setup on HA clusters

go.mod, go.sum, internal/dctr/run.go, pkg/registry/registry.go, pkg/registry/registry_test.go
I'm trying to build a cli tool that provisions a kind clusters, applies some manifests, configures some helm repos and applies some others. 
I've been hitting an issue with this dependency as the version 2.8.3 has a file which does not compile as the package it's depending on [here](https://github.com/distribution/distribution/blob/4772604ae973031ab32dd9805a4bccf61d94909f/reference/reference_deprecated.go#L122) remove this function in a later version and i'm seeing an error when building:
This PR updates to use the "good" package, local tests are passing, haven't tried with e2e but my local test (build a kind cluster with registry and delete it, works)
=> Remove deprecated version of docker/reference as its conflicting with a helm client library

pkg/cluster/docker_desktop.go
DD 4.35 flattens the settings response without this.
=> dd: add `?format=grouped` parameter to /app/settings

pkg/api/generated.deepcopy.go, pkg/api/types.go, pkg/cmd/get.go, pkg/registry/registry.go, pkg/registry/registry_test.go
noticed while poking around on https://github.com/tilt-dev/tilt/issues/6457
i'm not sure this is actually the underlying problem
but it's good to clean up anyway.
=> registry: improve error handling on port status

examples/kind_extra_args.yaml, pkg/api/types.go, pkg/cluster/admin_kind.go
- Allows passing arbitrary extra arguments to `kind`. This is useful for several debugging scenarios and edge cases, described in the `kind_extra_args.yaml` file I included.
=> [feat] support passing extra args to `kind create`

examples/kind_registry_auth.yaml, pkg/api/types.go, pkg/cluster/admin_docker_desktop.go, pkg/cluster/admin_k3d.go, pkg/cluster/admin_kind.go, pkg/cluster/admin_kind_test.go, pkg/cluster/admin_minikube.go
- Motivation: https://github.com/tilt-dev/ctlptl/issues/355
- In my "real" Kubernetes clusters, I use ECR as an image registry. Nodes are automatically authorized/configured to pull from ECR through a combination of IAM and containerd settings.
- I want my Tilt Kubernetes clusters to mirror "real" clusters as much as possible. I want to avoid making Tilt-specific modifications to Kubernetes manifests to make them work (see discussion in https://github.com/tilt-dev/ctlptl/issues/355).
- There currently isn't a way to achieve both of these goals simulaneously:
- I _could_ use some combination of `docker pull && docker push` or  `kind load`, though this makes the Tilt configuration clunky.
- I _could_ provide `imagePullSecrets`, but this causes the Tilt configuration to deviate from the …
=> [feat] pull-through caching/proxying for images
